In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A.shape

(3, 3)

In [5]:
vector = np.array([1, 2, 3])
vector

array([1, 2, 3])

In [6]:
vector.shape

(3,)

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To access element in matrix with index

In [8]:
A[1, :]

array([4, 5, 6])

In [9]:
#or
A[1]

array([4, 5, 6])

In [10]:
A[:, 2]

array([3, 6, 9])

In [11]:
#to access element 8
A[2, 1]

8

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.diag(A) # diagonal element of matrix A

array([1, 5, 9])

In [14]:
np.diag(np.diag(A)) #element diag of A to new matrix diagonal

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [15]:
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
A @ np.eye(3) # Matrix A multiply by identity matrix

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
np.zeros((3, 3)) # matrix with all element are zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Arithmatic Operation

In [19]:
B = np.array([[2, 1, 1],
              [1, 0, 3],
              [0, 1, 2]])
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

Addition

In [20]:
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
A + B

array([[ 3,  3,  4],
       [ 5,  5,  9],
       [ 7,  9, 11]])

In [22]:
vector

array([1, 2, 3])

In [23]:
A + vector # matrix with vector

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [24]:
C = np.array([[2, 2, 3],
              [1, 4, 2]])

C

array([[2, 2, 3],
       [1, 4, 2]])

In [25]:
A + C # error, those A & C doesn't have the same dimension

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

Substraction

In [ ]:
10 - A #with scalar

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
B - A

array([[ 1, -1, -2],
       [-3, -5, -3],
       [-7, -7, -7]])

Division

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

In [ ]:
A / 2 # with scalar

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
A / B # look after for "divided by zero" case

C:\Users\lenovo\AppData\Local\Temp\ipykernel_15936\3006334257.py:1: RuntimeWarning: divide by zero encountered in true_divide
  A / B


array([[0.5, 2. , 3. ],
       [4. , inf, 2. ],
       [inf, 8. , 4.5]])

Multiplication

In [ ]:
A * 10 # with scalar

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

In [ ]:
A * B # hadamard product -- element wise multiplication

array([[ 2,  2,  3],
       [ 4,  0, 18],
       [ 0,  8, 18]])

In [ ]:
A @ B # matrix multiplication (Dot)

array([[ 4,  4, 13],
       [13, 10, 31],
       [22, 16, 49]])

In [ ]:
F = np.array([[2, 1, 0],
              [0, 2, 2],
              [1, 0, 1],
              [3, 0, 1]])
F

array([[2, 1, 0],
       [0, 2, 2],
       [1, 0, 1],
       [3, 0, 1]])

In [ ]:
G = np.array([[1, 0],
              [0, 4],
              [5, 2]])
G

array([[1, 0],
       [0, 4],
       [5, 2]])

In [ ]:
F @ G

array([[ 2,  4],
       [10, 12],
       [ 6,  2],
       [ 8,  2]])

In [ ]:
G @ F # error, rows of G != columns of F

# rule of dot matrix (n?,k),(k,m?)->(n?,m?)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

---

Transpose

In [ ]:
G

array([[1, 0],
       [0, 4],
       [5, 2]])

In [ ]:
G.T # Transpose

array([[1, 0, 5],
       [0, 4, 2]])

---

Invers

In [ ]:
B

array([[2, 1, 1],
       [1, 0, 3],
       [0, 1, 2]])

In [ ]:
B_inv = np.linalg.inv(B)
B @ B_inv

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
S = np.array([[2, 5, 1],
              [4, 10, 2],
              [3, 1, 1]])
S

array([[ 2,  5,  1],
       [ 4, 10,  2],
       [ 3,  1,  1]])

In [ ]:
np.linalg.inv(S) # S is a singular matrix - singular matrix doesn't have invers

LinAlgError: Singular matrix

---

Determinant

In [ ]:
K = np.array([[2, 1],
              [2, 8]])
K

array([[2, 1],
       [2, 8]])

In [ ]:
np.linalg.det(K)

13.999999999999996

In [ ]:
J = np.array([[8, -1],
              [-2, 2]])
J / 14

array([[ 0.57142857, -0.07142857],
       [-0.14285714,  0.14285714]])

In [ ]:
np.linalg.inv(K)

array([[ 0.57142857, -0.07142857],
       [-0.14285714,  0.14285714]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.linalg.inv(A) # A is a singular matrix - singular matrix doesn't have invers

LinAlgError: Singular matrix

In [ ]:
np.linalg.det(A)

0.0

That's why A doesn't have invers, its determinant is zero

---

Tensor

In [ ]:
M1 = np.array([[1, 1, 8],
               [2, 5, 1]])
M2 = np.array([[1, 8, 7],
               [2, 0, 0]])
M3 = np.array([[9, 3, 8],
               [2, 3, 12]])
M4 = np.array([[14, 14, 8],
               [2, 7, 1]])

In [ ]:
tensor = np.array([M1, M2, M3, M4])
tensor

array([[[ 1,  1,  8],
        [ 2,  5,  1]],

       [[ 1,  8,  7],
        [ 2,  0,  0]],

       [[ 9,  3,  8],
        [ 2,  3, 12]],

       [[14, 14,  8],
        [ 2,  7,  1]]])

In [ ]:
tensor.shape

(4, 2, 3)